name: $(Build.SourceBranchName).$(Date:yyyyMMdd).$(Rev:r)
trigger:
  - main

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build

        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - template: .azurepipelines/build-template.yaml

  - stage: CI_Deploy
    displayName: Deploy to CI
    jobs:
      - deployment: DeployWebApp
        displayName: Deploy Web App

        pool:
          vmImage: 'ubuntu-latest'

        environment: ci
        strategy:
          runOnce:
            deploy:
              steps:
                - template: .azurepipelines/deployment-template.yaml
                  parameters:
                    environmentName: ci

  - stage: PROD_Deploy
    displayName: Deploy to Production
    jobs:
      - deployment: DeployWebApp
        displayName:

        pool:
          vmImage: 'ubuntu-latest'

        environment: PROD
        strategy:
          runOnce:
            deploy:
              steps:
                - template: .azurepipelines/deployment-template.yaml
                  parameters:
                    environmentName: prod
