name: $(Build.SourceBranchName).$(Date:yyyyMMdd).$(Rev:r)

schedules:
  - cron: '0 0 * * Wed'
    displayName: Daily midnight build
    branches:
      include:
        - develop

pr: none

trigger: none

stages:
  - stage: Analysis
    displayName: Audit Packages for vulnurabilities and for outdated packages.
    jobs:
      - job: Analysis
        displayName: Audit Packages for vulnurabilities and for outdated packages.

        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - script: yarn audit
            displayName: yarn audit

          - script: yarn outdated
            displayName: yarn outdated
            condition: succeededOrFailed()
